version: "3.0" # docker-compose version
services:
  urlShortener:
    container_name: urlShortener
    restart: unless-restart
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: YOUR_MONGO_URI
